name: Release

on:
  push:
    branches:
      - '*'
      - '!main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install 

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update GitHub Release
        if: steps.changesets.outputs.releaseNeeded == 'true'
        run: |
          changelog=$(cat .changeset/*.md)
          prerelease=true # Set to false for a regular release, true for a pre-release
          body="### Changelog\n\n$changelog"

          echo "Creating GitHub Release..."
          curl -X POST -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
            -d "{\"tag_name\":\"${{ steps.changesets.outputs.releasePlan.tag }}\",\"name\":\"${{ steps.changesets.outputs.releasePlan.tag }}\",\"body\":\"$body\",\"prerelease\":$prerelease}" \
            "https://api.github.com/repos/${{ github.repository }}/releases"

        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
