name: Prerelease Workflow

on:
  push:
    branches:
      - '*'
      - '!main'

permissions:
  contents: write
  pull-requests: write

jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
    - name: Print Branch Name
      run: echo ${{ github.ref }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Check Prerelease Status
      id: check_prerelease
      run: echo "::set-output name=PRERELEASE_STATUS::$(if [ -d ".changeset" ]; then echo "true"; else echo "false"; fi)"

    - name: Enter or Verify Prerelease Mode
      run: |
        if [ "${{ steps.check_prerelease.outputs.PRERELEASE_STATUS }}" == "true" ]; then
          echo "Already in prerelease mode";
        else
          npx changeset pre enter next;
          npx changeset version;
          echo "Entered prerelease mode";
        fi

    - name: Publish Prerelease
      run: npx changeset publish

    - name: Publish GitHub Release
      if: steps.check_prerelease.outputs.PRERELEASE_STATUS == 'true'
      run: |
        PRERELEASE_VERSION=$(jq -r '.[0].release' .changeset/*.json)
        gh release create "$PRERELEASE_VERSION" --title "Prerelease - $PRERELEASE_VERSION" --notes "$(cat .changeset/*.md)" --draft

    - name: Push Changes and Tags
      run: git push --follow-tags
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}